name: Ruff

on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "*.md"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3

      - name: Check formatting
        run: ruff format --check --diff .

      - name: Check linting
        run: ruff check --output-format=github .
